name:                sgm-api
version:             0.1.0.0
github:              "krawitzzz/sgm-api"
license:             BSD3
author:              "Nikita Demin"
maintainer:          "example@example.com"
copyright:           "2021 Nikita Demin"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         SGM-API

dependencies:
- base >= 4.7 && < 5
- rio
- aeson
- beam-core
- beam-migrate
- beam-postgres
- bytestring
- containers
- data-default
- di-core
- di-monad
- directory
- dlist
- dotenv
- fast-logger
- http-types
- http-api-data
- lifted-async
- monad-time
- mtl
- safe-exceptions
- servant-server
- servant-exceptions
- servant-exceptions-server
- servant-errors
- string-conversions
- time
- uuid
- wai
- wai-extra
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
#default
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns
# custom stuff
- DeriveAnyClass
- DerivingStrategies
- OverloadedLabels
- TemplateHaskell
- TypeApplications
- TypeOperators
- UndecidableInstances
- QuasiQuotes

library:
  source-dirs: src

executables:
  sgm-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - sgm-api

tests:
  sgm-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - sgm-api
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
