version: '3.5'
services:
    sgm-api:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/sgm-api:cached
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        networks:
            - sgm-api-gateway
            - sgm-api-db

    postgres:
        image: postgres:10
        container_name: sgm-api-postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_MULTIPLE_DATABASES: sgm_api,sgm_api_test
        networks:
            - sgm-api-db
        ports:
            - 5444:5432
        volumes:
            - ./pg-init-scripts:/docker-entrypoint-initdb.d

networks:
    sgm-api-gateway:
        driver: bridge
        name: sgm-api-gateway
    sgm-api-db:
        driver: bridge
        name: sgm-api-db
